# ===== APLICAÇÃO =====
spring.application.name=AgroManager-API

# ===== BANCO DE DADOS =====
spring.datasource.url=jdbc:postgresql://${DB_HOST}/AgroManager-API
spring.datasource.username=${DB_USER}
spring.datasource.password=${MINHA_SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== FLYWAY =====
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# ===== JWT =====
jwt.secret=agromanager-chave-secreta-fixa-super-longa-minimo-32-caracteres-2026
jwt.expiration=86400000

# ===== SWAGGER =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

